language: php
php:
  - '5.6'
before_script:
  - composer self-update
  - composer install --no-interaction
script:
  - vendor/bin/phpunit

notifications:
  hipchat:
    rooms:
    - VIbRiKzT1EpuVN72HQ8BPv3zMLsnH4bFoZ4PuQdQ@Deployment
    template:
     - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html